import { Link } from 'react-router-dom';
import { ArrowLeft, ShieldAlert } from 'lucide-react';
import EyebrowLabel from '@/components/shared/EyebrowLabel';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-void py-16 px-5 md:px-8 text-chalk-hi">
      <div className="mx-auto max-w-4xl space-y-10">
        <div>
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-body-sm text-chalk-lo hover:text-lime transition-colors mb-6"
          >
            <ArrowLeft className="h-4 w-4" /> Back to CashTwin
          </Link>
          <EyebrowLabel filled>Legal &amp; Compliance</EyebrowLabel>
          <h1 className="mt-4 font-display text-display-lg text-chalk-hi">Terms and Conditions</h1>
          <p className="mt-2 font-display text-lg text-lime">
            CashTwin — Consent-Based Cash-Flow Digital Twin
          </p>
          <p className="mt-1 text-body-sm text-chalk-lo">
            Last updated: 16 August 2026
          </p>
        </div>

        {/* Legal Advisory Note */}
        <div className="rounded-xl border border-caution/30 bg-caution/10 p-5 text-body-sm text-caution-lo flex items-start gap-3.5">
          <ShieldAlert className="h-5 w-5 text-caution shrink-0 mt-0.5" />
          <p className="text-body-sm leading-relaxed">
            <strong className="text-caution font-semibold">Note:</strong> This is a starting template drafted for a hackathon/demo product. Before using this with real users or real financial data, have it reviewed by a qualified lawyer familiar with Indian data-protection and fintech regulations (e.g. DPDP Act 2023, RBI guidelines on account aggregators/lending-adjacent tools, as applicable).
          </p>
        </div>

        <div className="space-y-8 text-chalk-hi/90 leading-relaxed border-t border-edge-dark pt-8">
          <section className="space-y-3">
            <h2 className="font-display text-heading-sm text-chalk-hi">1. Acceptance of Terms</h2>
            <p className="text-body-sm text-chalk-lo">
              By accessing or using CashTwin (&ldquo;the Platform&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;), you agree to be bound by these Terms and Conditions (&ldquo;Terms&rdquo;). If you do not agree to these Terms, please do not use the Platform.
            </p>
            <p className="text-body-sm text-chalk-lo">
              CashTwin is designed for use by owners and authorized representatives of micro, small, and medium enterprises (&ldquo;MSMEs&rdquo;, &ldquo;you&rdquo;, &ldquo;your business&rdquo;) operating in India.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-heading-sm text-chalk-hi">2. What CashTwin Is — and Is Not</h2>
            <p className="text-body-sm text-chalk-lo">
              CashTwin provides decision-support tools — cash-flow forecasting, payment behaviour analysis, anomaly detection, and recovery-option comparisons — based on data you choose to share with it.
            </p>
            <div className="rounded-lg border border-edge-dark bg-surface p-4 space-y-2 text-body-sm text-chalk-lo">
              <p className="font-medium text-chalk-hi">CashTwin does not:</p>
              <ul className="list-disc pl-5 space-y-1.5 text-chalk-lo">
                <li>Initiate, approve, reject, or facilitate any loan, credit line, or lending decision</li>
                <li>Act as a lender, broker, or financial advisor</li>
                <li>Guarantee the accuracy of any forecast, prediction, or projection</li>
                <li>Replace the advice of a qualified accountant, financial advisor, or legal professional</li>
              </ul>
            </div>
            <p className="text-body-sm text-chalk-lo">
              All forecasts, risk scores, and recommendations generated by the Platform are estimates based on historical data and statistical/machine-learning models. They are provided for informational purposes only and should not be treated as guaranteed outcomes.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-heading-sm text-chalk-hi">3. Consent and Data Access</h2>
            <p className="text-body-sm text-chalk-lo">
              CashTwin operates on a consent-first basis. We will not analyse any category of your data unless you have explicitly enabled it in your account settings.
            </p>
            <p className="text-body-sm text-chalk-lo">You may, at any time:</p>
            <ul className="list-disc pl-5 space-y-1.5 text-body-sm text-chalk-lo">
              <li>Review exactly what data categories you have authorized us to access</li>
              <li>Revoke consent for any category, which takes effect immediately</li>
              <li>Request a copy of your audit log showing when and how consent settings were changed</li>
            </ul>
            <p className="text-body-sm text-chalk-lo">
              Categories of data you may choose to share include, but are not limited to: invoice records, payment history, and forecasting inputs. Sharing your data with third parties (such as lenders or advisors) is strictly opt-in and disabled by default.
            </p>
            <p className="text-body-sm text-chalk-lo">
              For full detail on how we collect, use, and protect your data, please see our{' '}
              <Link to="/privacy" className="text-lime underline underline-offset-2 hover:text-chalk-hi">
                Privacy Policy
              </Link>
              .
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-heading-sm text-chalk-hi">4. Accuracy of Imported Data</h2>
            <p className="text-body-sm text-chalk-lo">
              CashTwin may use optical character recognition (OCR) and automated extraction to read data from invoices and documents you upload. While we assign confidence scores to extracted values and flag low-confidence fields for your review, you are responsible for verifying the accuracy of imported data before relying on any forecast or output derived from it.
            </p>
            <p className="text-body-sm text-chalk-lo">
              You may correct any imported value at any time; corrections will cause dependent forecasts to recalculate.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-heading-sm text-chalk-hi">5. User Responsibilities</h2>
            <p className="text-body-sm text-chalk-lo">You agree to:</p>
            <ul className="list-disc pl-5 space-y-1.5 text-body-sm text-chalk-lo">
              <li>Provide accurate information when creating and maintaining your account</li>
              <li>Use the Platform only for lawful business purposes</li>
              <li>Not attempt to reverse-engineer, misuse, or interfere with the Platform&apos;s underlying models or infrastructure</li>
              <li>Keep your login credentials confidential and notify us promptly of any unauthorized access</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-heading-sm text-chalk-hi">6. Limitation of Liability</h2>
            <p className="text-body-sm text-chalk-lo">
              To the maximum extent permitted by applicable law, CashTwin and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from:
            </p>
            <ul className="list-disc pl-5 space-y-1.5 text-body-sm text-chalk-lo">
              <li>Reliance on forecasts, projections, or recommendations generated by the Platform</li>
              <li>Business decisions made based on Platform outputs</li>
              <li>Errors or delays in data processing, including OCR extraction errors</li>
              <li>Interruptions, downtime, or unavailability of the Platform</li>
            </ul>
            <p className="text-body-sm text-chalk-lo">
              The Platform is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis, without warranties of any kind, express or implied.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-heading-sm text-chalk-hi">7. Intellectual Property</h2>
            <p className="text-body-sm text-chalk-lo">
              All content, branding, models, and underlying technology of the Platform are the property of CashTwin or its licensors. Nothing in these Terms grants you any right to use CashTwin&apos;s trademarks, logos, or proprietary technology outside of your authorized use of the Platform.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-heading-sm text-chalk-hi">8. Changes to These Terms</h2>
            <p className="text-body-sm text-chalk-lo">
              We may update these Terms from time to time. Material changes will be communicated to you through the Platform or via the contact details associated with your account. Continued use of the Platform after changes take effect constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-heading-sm text-chalk-hi">9. Termination</h2>
            <p className="text-body-sm text-chalk-lo">
              We reserve the right to suspend or terminate your access to the Platform if you violate these Terms. You may stop using the Platform and request account/data deletion at any time through your account settings.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-heading-sm text-chalk-hi">10. Governing Law</h2>
            <p className="text-body-sm text-chalk-lo">
              These Terms shall be governed by and construed in accordance with the laws of India, without regard to conflict-of-law principles. Any disputes shall be subject to the exclusive jurisdiction of the courts of Mumbai, Maharashtra.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="font-display text-heading-sm text-chalk-hi">11. Contact Us</h2>
            <p className="text-body-sm text-chalk-lo">
              If you have questions about these Terms, please contact us at:{' '}
              <a href="mailto:support@cashtwin.in" className="text-lime underline underline-offset-2 hover:text-chalk-hi">
                support@cashtwin.in
              </a>{' '}
              or visit our{' '}
              <Link to="/contact" className="text-lime underline underline-offset-2 hover:text-chalk-hi">
                Contact Page
              </Link>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
